const PLAYERS = (window.PLAYER_CHUNKS || []).flat();
const DEFAULTS = {teams:10,slot:8,rounds:15,method:'Snake',scoring:'Full PPR',strategy:'Balanced',specialRound:12,slots:{QB:1,RB:2,WR:2,TE:1,FLEX:1,K:1,DST:1,BENCH:6}};
const KEY='fantasyDraft2026CommandCenter_v2';
let state={settings:structuredClone(DEFAULTS),draft:[],targets:[],notes:{},selected:null,filterPos:'ALL',tierPos:'RB',search:'',targetsOnly:false};
let activeView='command';
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x){state={...state,...x,settings:{...DEFAULTS,...x.settings,slots:{...DEFAULTS.slots,...(x.settings?.slots||{})}}};}}catch(e){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function $ (s){return document.querySelector(s)}
function $$ (s){return [...document.querySelectorAll(s)]}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1500)}
function pById(id){return PLAYERS.find(p=>p.id===id)}
function rankFor(p){if(state.settings.scoring==='Half PPR')return p.halfRank||p.rank||999;if(state.settings.scoring==='Standard')return p.stdRank||p.rank||999;return p.rank||999}
function currentPick(){return state.draft.length+1}
function roundForPick(n){return Math.floor((n-1)/state.settings.teams)+1}
function teamAtPick(n){const t=state.settings.teams;const r=roundForPick(n);let idx=(n-1)%t;if(state.settings.method==='Snake'&&r%2===0) return t-idx;return idx+1}
function nextMyPicks(from=currentPick(),count=3){const out=[],max=state.settings.teams*state.settings.rounds;for(let p=from;p<=max&&out.length<count;p++){if(teamAtPick(p)===state.settings.slot)out.push(p)}return out}
function recommendationPick(){const cp=currentPick();return nextMyPicks(cp,1)[0]||cp}
function isTaken(id){return state.draft.some(d=>d.playerId===id)}
function isMine(id){return state.draft.some(d=>d.playerId===id&&d.mine)}
function isTarget(id){return state.targets.includes(id)}
function available(){return PLAYERS.filter(p=>!isTaken(p.id))}
function playerTrend(p){if(p.trend==null||p.trend===0)return {text:'—',cls:'flat'};return p.trend>0?{text:'▲ '+p.trend,cls:'up'}:{text:'▼ '+Math.abs(p.trend),cls:'down'}}
function valueAtPick(p,pick=currentPick()){const d=pick-rankFor(p);if(d>=8)return {text:'+'+d,cls:'good'};if(d<=-12)return {text:String(d),cls:'reach'};return {text:d>0?'+'+d:String(d),cls:'neutral'}}
function posClass(pos){return `<span class="pos ${pos}">${pos}</span>`}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function assignRoster(){
 const mine=state.draft.filter(d=>d.mine).map(d=>pById(d.playerId)).filter(Boolean);const slots=[];const used=new Set();
 const addDirect=(pos,n)=>{for(let i=0;i<n;i++){const idx=mine.findIndex((p,j)=>!used.has(j)&&p.pos===pos);if(idx>=0){used.add(idx);slots.push({label:pos,player:mine[idx]})}else slots.push({label:pos,player:null})}};
 addDirect('QB',state.settings.slots.QB);addDirect('RB',state.settings.slots.RB);addDirect('WR',state.settings.slots.WR);addDirect('TE',state.settings.slots.TE);
 for(let i=0;i<state.settings.slots.FLEX;i++){const idx=mine.findIndex((p,j)=>!used.has(j)&&['RB','WR','TE'].includes(p.pos));if(idx>=0){used.add(idx);slots.push({label:'FLEX',player:mine[idx]})}else slots.push({label:'FLEX',player:null})}
 addDirect('K',state.settings.slots.K);addDirect('DST',state.settings.slots.DST);
 const leftovers=mine.map((p,i)=>({p,i})).filter(x=>!used.has(x.i)).map(x=>x.p);for(let i=0;i<state.settings.slots.BENCH;i++)slots.push({label:'BN',player:leftovers[i]||null});
 return {slots,mine,leftovers};
}
function counts(){const c={QB:0,RB:0,WR:0,TE:0,K:0,DST:0};assignRoster().mine.forEach(p=>c[p.pos]=(c[p.pos]||0)+1);return c}
function needBonus(pos,round){const c=counts(),s=state.settings.slots;let b=0;
 if(pos==='QB'&&c.QB<s.QB)b+=13;if(pos==='RB'&&c.RB<s.RB)b+=17;if(pos==='WR'&&c.WR<s.WR)b+=17;if(pos==='TE'&&c.TE<s.TE)b+=13;if(pos==='K'&&c.K<s.K&&round>=state.settings.specialRound)b+=10;if(pos==='DST'&&c.DST<s.DST&&round>=state.settings.specialRound)b+=10;
 const eligible=c.RB+c.WR+c.TE, needed=s.RB+s.WR+s.TE+s.FLEX;if(['RB','WR','TE'].includes(pos)&&eligible<needed)b+=5;
 if((pos==='QB'&&c.QB>=s.QB)||(pos==='TE'&&c.TE>=s.TE))b-=7;
 return b;
}
function scarcityBonus(p){const av=available().filter(x=>x.pos===p.pos).sort((a,b)=>rankFor(a)-rankFor(b));const same=av.filter(x=>x.posTier===p.posTier);const later=av.filter(x=>(x.posTier||99)>(p.posTier||99));let b=0;if(same.length<=2)b+=5;else if(same.length<=4)b+=2;if(later.length){const gap=rankFor(later[0])-rankFor(p);if(gap>=12)b+=6;else if(gap>=7)b+=3}return b}
function strategyAdjust(p,r){const st=state.settings.strategy,c=counts();if(st==='Best Player Available')return -needBonus(p.pos,r)*.45;if(st==='Late QB'&&p.pos==='QB'&&r<7&&p.posTier>1)return -15;if(st==='Hero RB'){if(p.pos==='RB'&&c.RB===0&&r<=2)return 12;if(p.pos==='RB'&&c.RB>=1&&r<=5)return -8;if(p.pos==='WR'&&c.RB>=1&&r<=5)return 5}if(st==='Zero RB'){if(p.pos==='RB'&&r<=4)return -15;if(['WR','TE'].includes(p.pos)&&r<=4)return 7}if(st==='WR Heavy'&&p.pos==='WR'&&r<=6)return 8;return 0}
function byePenalty(p){const byes={};assignRoster().mine.forEach(x=>{byes[x.bye]=(byes[x.bye]||0)+1});return (byes[p.bye]||0)>=3?-4:0}
function scorePlayer(p,pk=recommendationPick()){const r=roundForPick(pk),rank=rankFor(p);let score=140-rank*.72;const fall=pk-rank;score+=Math.max(-18,Math.min(25,fall))*1.18;score+=needBonus(p.pos,r)+scarcityBonus(p)+(isTarget(p.id)?13:0)+strategyAdjust(p,r)+byePenalty(p);
 if(['K','DST'].includes(p.pos)&&r<state.settings.specialRound)score-=75;if(p.news?.tag==='RISER'||p.news?.tag==='TARGET')score+=2;if(p.news?.tag==='RISK'||p.news?.tag==='FALLER')score-=2;return score}
function reasonFor(p,pick=recommendationPick()){const r=roundForPick(pick),reasons=[];const v=pick-rankFor(p);if(v>=8)reasons.push(`${v}-pick value fall`);else if(v<=-10)reasons.push(`${Math.abs(v)} picks ahead of board`);else reasons.push(`rank ${rankFor(p)} fits this range`);
 const nb=needBonus(p.pos,r);if(nb>=12)reasons.push(`fills an open ${p.pos} starter`);else if(nb>0)reasons.push('helps roster construction');
 const sc=scarcityBonus(p);if(sc>=5)reasons.push('tier cliff / scarce option');if(isTarget(p.id))reasons.push('your starred target');if(p.news?.tag==='RISER')reasons.push('market riser');if(p.news?.tag==='RISK')reasons.push('price includes notable risk');
 return reasons.slice(0,3).join(' • ')}
function recommendations(){const pick=recommendationPick();return available().slice().sort((a,b)=>scorePlayer(b,pick)-scorePlayer(a,pick)).slice(0,5)}
function nextBestPlayer(currentId){const recs=recommendations();return recs.find(p=>p.id!==currentId)||recs[0]||null}

function renderTop(){const cp=currentPick(),round=roundForPick(cp),team=teamAtPick(cp),total=state.settings.teams*state.settings.rounds;$('#topCurrentPick').textContent=cp>total?'Complete':`Pick ${cp}`;$('#topCurrentTeam').textContent=cp>total?'—':team===state.settings.slot?'YOU':`Team ${team}`;$('#topCurrentTeam').classList.toggle('accent',team===state.settings.slot);const next=nextMyPicks(cp,1)[0];$('#topNextPick').textContent=next||'—';$('#topRound').textContent=`${Math.min(round,state.settings.rounds)} / ${state.settings.rounds}`;$('#draftProgress').textContent=`${state.draft.length} / ${total}`;$('#mineCount').textContent=state.draft.filter(d=>d.mine).length;$('#targetsLeft').textContent=state.targets.filter(id=>!isTaken(id)).length;$('#nextPicks').innerHTML=nextMyPicks(cp,4).map(x=>`<span class="pick-pill">${x}</span>`).join('')||'<span class="subtle">Draft complete</span>';$('#strategyLabel').textContent=state.settings.strategy;$('#undoBtn').disabled=!state.draft.length;$('#mobilePick').textContent=currentPick();$('#mobileRound').textContent=roundForPick(currentPick());$('#mobileNext').textContent=nextMyPicks(currentPick(),1)[0]||'—'}
function renderRoster(){const a=assignRoster();$('#rosterSlots').innerHTML=a.slots.map(s=>`<div class="slot ${s.player?'':'empty'}"><div class="slot-label">${s.label}</div><div class="slot-player">${s.player?`${escapeHtml(s.player.name)} <span class="mini">${s.player.team} • ${s.player.pos}</span>`:'Open'}</div></div>`).join('');const filled=a.slots.filter(s=>s.player).length;$('#rosterStatus').textContent=`${filled}/${a.slots.length}`}
function renderChips(){const poss=['ALL','QB','RB','WR','TE','K','DST'];$('#posChips').innerHTML=poss.map(p=>`<button class="chip ${state.filterPos===p?'active':''}" data-pos="${p}">${p}</button>`).join('');$$('#posChips .chip').forEach(b=>b.onclick=()=>{state.filterPos=b.dataset.pos;save();renderBoard()})}
function filteredPlayers(){let av=available();const r=roundForPick(currentPick());if(state.filterPos!=='ALL')av=av.filter(p=>p.pos===state.filterPos);else if(r<state.settings.specialRound)av=av.filter(p=>!['K','DST'].includes(p.pos));if(state.targetsOnly)av=av.filter(p=>isTarget(p.id));if(state.search.trim()){const q=state.search.trim().toLowerCase();av=av.filter(p=>(p.name+' '+p.team+' '+p.pos).toLowerCase().includes(q))}return av.sort((a,b)=>rankFor(a)-rankFor(b))}
function renderBoard(){renderChips();const list=filteredPlayers();$('#availableCount').textContent=`${list.length} shown • ${available().length} available`;$('#playerRows').innerHTML=list.map(p=>{const t=playerTrend(p),v=valueAtPick(p),selected=state.selected===p.id;return `<tr class="player-row ${selected?'selected':''}" data-id="${p.id}"><td class="star ${isTarget(p.id)?'on':''}" data-star="${p.id}">${isTarget(p.id)?'★':'☆'}</td><td class="rank">${rankFor(p)}</td><td><div class="player-name">${escapeHtml(p.name)}${p.news?`<span class="news-tag ${p.news.tone}">${p.news.tag}</span>`:''}</div><div class="player-meta">${p.source?.startsWith('RotoWire')?'2026 live board':'depth board'}</div></td><td>${posClass(p.pos)} <span class="subtle">${p.posRank||''}</span></td><td class="tier">${p.posTier||p.tier||'—'}</td><td class="hide-mobile">${p.team} <span class="subtle">• bye ${p.bye}</span></td><td class="hide-mobile"><span class="trend ${t.cls}">${t.text}</span></td><td><span class="value-badge ${v.cls}">${v.text}</span></td></tr>`}).join('')||'<tr><td colspan="8"><div class="empty-state">No available players match these filters.</div></td></tr>';
 $('#mobilePlayerList').innerHTML=list.map(p=>{const v=valueAtPick(p),selected=state.selected===p.id;return `<div class="mobile-player-card ${selected?'selected':''}" data-mobile-id="${p.id}"><div class="mobile-rank">${rankFor(p)}</div><div class="mobile-player-main"><div class="mobile-player-name">${escapeHtml(p.name)}${p.news?` <span class="news-tag ${p.news.tone}">${p.news.tag}</span>`:''}</div><div class="mobile-player-meta">${posClass(p.pos)} <span>${p.team}</span><span>Bye ${p.bye}</span><span>Tier ${p.posTier||p.tier||'—'}</span><span>${p.posRank||''}</span></div></div><div class="mobile-player-side"><button class="mobile-star ${isTarget(p.id)?'on':''}" data-mobile-star="${p.id}" aria-label="Toggle target">${isTarget(p.id)?'★':'☆'}</button><span class="value-badge ${v.cls}">${v.text}</span></div></div>`}).join('')||'<div class="empty-state">No available players match these filters.</div>';
 $$('.player-row').forEach(row=>row.onclick=e=>{if(e.target.dataset.star)return;state.selected=row.dataset.id;save();renderAll()});$$('[data-star]').forEach(s=>s.onclick=e=>{e.stopPropagation();toggleTarget(s.dataset.star)});$$('[data-mobile-id]').forEach(card=>card.onclick=e=>{if(e.target.dataset.mobileStar)return;state.selected=card.dataset.mobileId;save();renderAll()});$$('[data-mobile-star]').forEach(s=>s.onclick=e=>{e.stopPropagation();toggleTarget(s.dataset.mobileStar)})}
function toggleTarget(id){state.targets=isTarget(id)?state.targets.filter(x=>x!==id):[...state.targets,id];save();renderAll();toast(isTarget(id)?'Target added':'Target removed')}
function chooseNextBest(currentId){const next=nextBestPlayer(currentId);if(!next)return;state.selected=next.id;save();renderAll();toast(`Next best: ${next.name}`)}
function renderSelected(){
 let p=pById(state.selected);
 if(!p||isTaken(p.id)){p=recommendations()[0];state.selected=p?.id||null}
 const mas=$('#mobileActionSheet');
 if(!p){$('#selectedPanel').innerHTML='<div class="empty-state">Draft complete.</div>';mas.classList.remove('show');mas.innerHTML='';return}
 const v=valueAtPick(p),next=nextMyPicks(currentPick()+1,1)[0],nextBest=nextBestPlayer(p.id);
 const survival=next?(rankFor(p)<=next+4?'unlikely to make it back':rankFor(p)>=next+12?'plausible to make it back':'coin-flip range'):'last pick window';
 $('#selectedPanel').innerHTML=`<div class="selected-card"><div class="selected-title">${posClass(p.pos)} ${escapeHtml(p.name)}</div><div class="subtle" style="margin-top:5px">${p.team} • Bye ${p.bye} • ${state.settings.scoring} rank ${rankFor(p)} • ${p.pos} ${p.posRank}</div><div style="margin-top:8px"><span class="value-badge ${v.cls}">${v.text} vs pick</span> <span class="subtle">• ${survival}</span></div>${p.news?`<div class="selected-note"><span class="news-tag ${p.news.tone}" style="margin-left:0">${p.news.tag}</span> ${escapeHtml(p.news.text)} <a href="${p.news.url}" target="_blank" rel="noopener" style="color:var(--accent2)">source</a></div>`:''}<textarea class="note-input" id="playerNote" placeholder="Your note on this player…">${escapeHtml(state.notes[p.id]||'')}</textarea><div class="selected-actions"><button class="button primary" id="mineBtn">Draft to My Team</button><button class="button" id="takenBtn">Mark Taken</button><button class="button" id="targetBtn">${isTarget(p.id)?'★ Unstar':'☆ Target'}</button><button class="button" id="nextBestBtn" ${nextBest?'':'disabled'}>Next Best</button></div><div class="keyboard"><span class="kbd">M</span> mine &nbsp; <span class="kbd">X</span> taken &nbsp; <span class="kbd">S</span> target</div></div>`;
 $('#mineBtn').onclick=()=>draftPlayer(p.id,true);
 $('#takenBtn').onclick=()=>draftPlayer(p.id,false);
 $('#targetBtn').onclick=()=>toggleTarget(p.id);
 $('#nextBestBtn').onclick=()=>chooseNextBest(p.id);
 $('#playerNote').oninput=e=>{state.notes[p.id]=e.target.value;save()};
 mas.innerHTML=`<div class="mobile-action-head"><div class="mobile-action-player"><strong>${escapeHtml(p.name)}</strong><span>${p.pos} ${p.posRank||''} • ${p.team} • rank ${rankFor(p)} • bye ${p.bye}</span></div><span class="value-badge ${v.cls}">${v.text}</span></div><div class="mobile-action-buttons"><button class="button primary" id="mobileMineBtn">Draft Mine</button><button class="button" id="mobileTakenBtn">Taken</button><button class="button star-action" id="mobileTargetBtn" aria-label="Toggle target">${isTarget(p.id)?'★':'☆'}</button><button class="button" id="mobileNextBestBtn" ${nextBest?'':'disabled'}>Next Best</button></div>`;
 mas.classList.toggle('show',activeView==='command');
 $('#mobileMineBtn').onclick=()=>draftPlayer(p.id,true);
 $('#mobileTakenBtn').onclick=()=>draftPlayer(p.id,false);
 $('#mobileTargetBtn').onclick=()=>toggleTarget(p.id);
 $('#mobileNextBestBtn').onclick=()=>chooseNextBest(p.id);
}
function draftPlayer(id,mine){if(isTaken(id))return;const cp=currentPick(),total=state.settings.teams*state.settings.rounds;if(cp>total){toast('Draft is already complete');return}const p=pById(id);state.draft.push({pick:cp,round:roundForPick(cp),team:teamAtPick(cp),playerId:id,mine:!!mine,ts:Date.now()});state.selected=null;save();renderAll();toast(`${p.name} → ${mine?'your team':'taken'}`)}
function undo(){const d=state.draft.pop();if(!d)return;state.selected=d.playerId;save();renderAll();toast('Last pick undone')}
function renderRecs(){const recs=recommendations();$('#recommendations').innerHTML=recs.slice(0,3).map((p,i)=>`<div class="rec" data-rec="${p.id}"><div class="rec-top"><div><span class="subtle">#${i+1}</span> <span class="rec-name">${escapeHtml(p.name)}</span> ${posClass(p.pos)}</div><div class="score">${Math.round(scorePlayer(p))}</div></div><div class="reasons">${escapeHtml(reasonFor(p))}</div></div>`).join('');$$('[data-rec]').forEach(x=>x.onclick=()=>{state.selected=x.dataset.rec;save();renderAll()});
 const top=recs[0];if(!top){$('#tierAlert').innerHTML='<strong>Draft complete</strong>No players remain.';$('#mobileRecommendation').innerHTML='<div class="mobile-best-copy"><div class="mobile-best-label">Draft complete</div><div class="mobile-best-name">No players remain</div></div>';return}const avSame=available().filter(x=>x.pos===top.pos&&x.posTier===top.posTier).sort((a,b)=>rankFor(a)-rankFor(b));const next=nextMyPicks(currentPick()+1,1)[0],plannedPick=recommendationPick(),plannedValue=valueAtPick(top,plannedPick);let msg=avSame.length<=2?`Only ${avSame.length} ${top.pos}(s) remain in Tier ${top.posTier}.`:`${avSame.length} ${top.pos}s remain in Tier ${top.posTier}.`;if(next)msg+=` You pick again at ${next}.`;$('#tierAlert').innerHTML=`<strong>Tier pulse</strong>${msg}`;$('#mobileRecommendation').innerHTML=`<div class="mobile-best-copy"><div class="mobile-best-label">Best fit for pick ${plannedPick}</div><div class="mobile-best-name">${escapeHtml(top.name)} ${posClass(top.pos)}</div><div class="mobile-best-reason">${escapeHtml(reasonFor(top,plannedPick))}</div></div><span class="value-badge ${plannedValue.cls}">${plannedValue.text}</span>`;$('#mobileRecommendation').onclick=()=>{state.selected=top.id;save();renderAll()}}
function renderTopFive(){
 const recs=recommendations(),pick=recommendationPick(),total=state.settings.teams*state.settings.rounds,c=counts(),s=state.settings.slots;
 const needs=['QB','RB','WR','TE','K','DST'].filter(pos=>(c[pos]||0)<(s[pos]||0)).map(pos=>`${pos} ${c[pos]||0}/${s[pos]||0}`);
 $('#topPicksAt').textContent=currentPick()>total?'Complete':`Pick ${pick}`;
 $('#topPicksContext').textContent=currentPick()>total?'Your draft is complete.':`${state.settings.strategy} strategy • ${state.draft.filter(d=>d.mine).length} players rostered • ${needs.length?`open starters: ${needs.join(', ')}`:'all starting slots covered'}`;
 $('#topPicksList').innerHTML=recs.map((p,i)=>{const value=valueAtPick(p,pick);return `<button type="button" class="top-pick-card" data-top-pick="${p.id}"><span class="top-pick-number">${i+1}</span><div class="top-pick-name">${escapeHtml(p.name)}</div><div class="top-pick-meta">${posClass(p.pos)} <span>${p.team} • Bye ${p.bye} • Rank ${rankFor(p)}</span></div><div class="top-pick-reason">${escapeHtml(reasonFor(p,pick))}</div><div class="top-pick-score"><span class="value-badge ${value.cls}">${value.text} vs pick</span><strong>Fit ${Math.round(scorePlayer(p,pick))}</strong></div></button>`}).join('')||'<div class="team-card empty-state">No players remain—the draft is complete.</div>';
 $$('[data-top-pick]').forEach(card=>card.onclick=()=>{state.selected=card.dataset.topPick;save();showView('command');renderAll()});
}
function renderTierBoard(){const poss=['QB','RB','WR','TE','K','DST'];$('#tierPosChips').innerHTML=poss.map(p=>`<button class="chip ${state.tierPos===p?'active':''}" data-tierpos="${p}">${p}</button>`).join('');$$('[data-tierpos]').forEach(b=>b.onclick=()=>{state.tierPos=b.dataset.tierpos;save();renderTierBoard()});const pos=state.tierPos;const all=PLAYERS.filter(p=>p.pos===pos).sort((a,b)=>(pTier(a)-pTier(b))||(rankFor(a)-rankFor(b)));const tiers=[...new Set(all.map(p=>pTier(p)))];$('#tierBoard').innerHTML=tiers.map(t=>{const ps=all.filter(p=>pTier(p)===t);const availCount=ps.filter(p=>!isTaken(p.id)).length;return `<div class="tier-block"><div class="tier-title"><b>${pos} Tier ${t}</b><span class="subtle">${availCount} available / ${ps.length}</span></div><div class="tier-players">${ps.map(p=>`<div class="tier-player ${isTaken(p.id)?'taken':''} ${isTarget(p.id)?'target':''}" data-tierplayer="${p.id}"><div class="line1">${isTarget(p.id)?'★':''} <strong>${escapeHtml(p.name)}</strong></div><div class="line2">#${rankFor(p)} • ${p.team} • Bye ${p.bye}${p.news?' • '+p.news.tag:''}</div></div>`).join('')}</div></div>`}).join('');$$('[data-tierplayer]').forEach(x=>x.onclick=()=>{if(isTaken(x.dataset.tierplayer))return;state.selected=x.dataset.tierplayer;showView('command');renderAll()})}
function pTier(p){return p.posTier||p.tier||99}
function renderTeam(){const a=assignRoster();$('#teamRosterFull').innerHTML=`<div class="roster-slots">${a.slots.map(s=>`<div class="slot ${s.player?'':'empty'}"><div class="slot-label">${s.label}</div><div class="slot-player">${s.player?`${escapeHtml(s.player.name)} <span class="mini">${s.player.pos} • ${s.player.team} • bye ${s.player.bye}</span>`:'Open'}</div></div>`).join('')}</div>`;const bye={};a.mine.forEach(p=>bye[p.bye]=(bye[p.bye]||0)+1);const max=Math.max(1,...Object.values(bye));$('#byeBars').innerHTML=[5,6,7,8,9,10,11,12,13,14].map(w=>`<div class="bye-bar-wrap"><div class="bye-bar" style="height:${((bye[w]||0)/max)*100}px" title="${bye[w]||0} player(s)"></div><div class="bye-label">W${w}<br>${bye[w]||0}</div></div>`).join('');const c=counts(),s=state.settings.slots;const needs=[];['QB','RB','WR','TE','K','DST'].forEach(pos=>{const req=s[pos]||0;if((c[pos]||0)<req)needs.push(`${pos} ${c[pos]||0}/${req}`)});const byecrowd=Object.entries(bye).filter(([w,n])=>n>=3).map(([w,n])=>`Week ${w}: ${n}`);$('#rosterRead').innerHTML=`<p><strong>Open starters:</strong> ${needs.length?needs.join(' • '):'None'}</p><p><strong>Bye clusters:</strong> ${byecrowd.length?byecrowd.join(' • '):'No major cluster yet'}</p><p class="subtle">Recommendation weights react to these openings, but strong value can still outrank a strict positional need.</p>`}
function renderLog(){const rows=state.draft.slice().reverse();$('#draftLog').innerHTML=rows.map(d=>{const p=pById(d.playerId);return `<tr class="${d.mine?'mine-row':''}"><td>${d.pick}</td><td>${d.round}</td><td>${d.mine?'YOU':'Team '+d.team}</td><td>${escapeHtml(p?.name||'Unknown')}</td><td>${p?posClass(p.pos):''}</td><td>${p?rankFor(p):'—'}</td></tr>`}).join('')||'<tr><td colspan="6"><div class="empty-state">No picks logged yet.</div></td></tr>'}
function renderSettings(){$('#setTeams').value=state.settings.teams;$('#setSlot').value=state.settings.slot;$('#setSlot').max=state.settings.teams;$('#setRounds').value=state.settings.rounds;$('#setMethod').value=state.settings.method;$('#setScoring').value=state.settings.scoring;$('#setStrategy').value=state.settings.strategy;$('#setSpecialRound').value=state.settings.specialRound;const labels=['QB','RB','WR','TE','FLEX','K','DST','BENCH'];$('#slotSettings').innerHTML=labels.map(k=>`<div class="field"><label>${k}</label><input type="number" min="0" max="12" value="${state.settings.slots[k]}" data-slotset="${k}"></div>`).join('');$$('[data-slotset]').forEach(i=>i.onchange=()=>{state.settings.slots[i.dataset.slotset]=Math.max(0,Number(i.value)||0);save();renderAll()})}
function applySettings(){state.settings.teams=Number($('#setTeams').value);state.settings.slot=Math.max(1,Math.min(state.settings.teams,Number($('#setSlot').value)||1));state.settings.rounds=Math.max(8,Number($('#setRounds').value)||15);state.settings.method=$('#setMethod').value;state.settings.scoring=$('#setScoring').value;state.settings.strategy=$('#setStrategy').value;state.settings.specialRound=Math.max(1,Number($('#setSpecialRound').value)||12);save();renderAll()}
function renderAll(){renderTop();renderRoster();renderBoard();renderSelected();renderRecs();renderTopFive();renderTierBoard();renderTeam();renderLog();renderSettings()}
function showView(v){activeView=v;$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===v));$$('[data-mobile-view]').forEach(t=>t.classList.toggle('active',t.dataset.mobileView===v));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));$('#mobileMoreMenu')?.classList.remove('show');$('#mobileActionSheet')?.classList.remove('show');if(v==='command')renderSelected();if(v==='picks')renderTopFive();if(v==='tiers')renderTierBoard();if(v==='team')renderTeam();if(v==='log')renderLog();if(v==='settings')renderSettings();window.scrollTo({top:0,behavior:'instant'})}
function download(filename,text,type='application/json'){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCSV(){const h=['Pick','Round','Team','Mine','Player','Pos','TeamAbbr','Bye','Rank'];const rows=state.draft.map(d=>{const p=pById(d.playerId);return [d.pick,d.round,d.team,d.mine?'Yes':'No',p?.name,p?.pos,p?.team,p?.bye,p?rankFor(p):'']});const esc=x=>`"${String(x??'').replaceAll('"','""')}"`;download('fantasy-draft-2026.csv',[h,...rows].map(r=>r.map(esc).join(',')).join('\n'),'text/csv')}
function resetAll(){if(!confirm('Reset the entire draft, targets, notes and settings?'))return;localStorage.removeItem(KEY);state={settings:structuredClone(DEFAULTS),draft:[],targets:[],notes:{},selected:null,filterPos:'ALL',tierPos:'RB',search:'',targetsOnly:false};renderAll();toast('Draft reset')}
let deferredInstallPrompt=null;
function backupState(){download('fantasy-draft-2026-state.json',JSON.stringify(state,null,2));toast('Backup downloaded')}
function closeMobileMore(){
 $('#mobileMoreMenu').classList.remove('show');
 if(activeView==='command')renderSelected();
}
function bind(){$$('.tab').forEach(t=>t.onclick=()=>showView(t.dataset.view));$$('[data-mobile-view]').forEach(t=>t.onclick=()=>showView(t.dataset.mobileView));$$('[data-more-view]').forEach(t=>t.onclick=()=>showView(t.dataset.moreView));$('#mobileMoreBtn').onclick=()=>{$('#mobileActionSheet').classList.remove('show');$('#mobileMoreMenu').classList.add('show')};$('#mobileCloseMore').onclick=closeMobileMore;$('#mobileMoreMenu').onclick=e=>{if(e.target===$('#mobileMoreMenu'))closeMobileMore()};$('#searchInput').oninput=e=>{state.search=e.target.value;renderBoard()};$('#targetsOnly').onchange=e=>{state.targetsOnly=e.target.checked;save();renderBoard()};$('#undoBtn').onclick=undo;$('#resetBtn').onclick=resetAll;$('#mobileResetBtn').onclick=resetAll;$('#saveBtn').onclick=backupState;$('#mobileSaveBtn').onclick=backupState;$('#csvBtn').onclick=exportCSV;$('#exportStateBtn').onclick=()=>download('fantasy-draft-2026-state.json',JSON.stringify(state,null,2));$('#importStateInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);state={...state,...x,settings:{...DEFAULTS,...x.settings,slots:{...DEFAULTS.slots,...(x.settings?.slots||{})}}};save();renderAll();toast('Draft state imported')}catch(err){alert('That JSON file could not be read.')}};rd.readAsText(f)};['setTeams','setSlot','setRounds','setMethod','setScoring','setStrategy','setSpecialRound'].forEach(id=>$('#'+id).onchange=applySettings);document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(!state.selected)return;if(e.key.toLowerCase()==='m')draftPlayer(state.selected,true);if(e.key.toLowerCase()==='x')draftPlayer(state.selected,false);if(e.key.toLowerCase()==='s')toggleTarget(state.selected)});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBtn').style.display='block'});$('#installBtn').onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installBtn').style.display='none'};if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});}
load();bind();state.selected=state.selected||recommendations()[0]?.id||null;$('#searchInput').value=state.search||'';$('#targetsOnly').checked=!!state.targetsOnly;renderAll();
